{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "smart-calendar.fullname" . }}
  labels:
    {{- include "smart-calendar.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host | quote }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      # Backend API routes - /api/* should go to backend service
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ include "smart-calendar.backend.name" . }}
            port:
              number: {{ .Values.backend.service.port }}
      # Frontend routes - all other paths go to frontend service
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "smart-calendar.frontend.name" . }}
            port:
              number: {{ .Values.frontend.service.port }}
{{- end }}
