apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smart-calendar.mongodb.secretName" . }}
  labels:
    {{- include "smart-calendar.labels" . | nindent 4 }}
type: Opaque
data:
+  # MongoDB connection string is base64-encoded here so values can stay readable
+  MONGO_URI: {{ .Values.mongodb.uri | b64enc | quote }}
